# Generated by Django 5.2.10 on 2026-02-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin/Temple Authority'), ('pilgrim', 'Pilgrim/Devotee')], default='pilgrim', max_length=10),
        ),
    ]
