# Generated by Django 5.2.10 on 2026-02-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('deity', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('AP', 'Andhra Pradesh'), ('TS', 'Telangana'), ('TN', 'Tamil Nadu'), ('KA', 'Karnataka'), ('KL', 'Kerala')], max_length=2)),
                ('district', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('image', models.ImageField(upload_to='temple_images/')),
                ('entry_gate_info', models.TextField(help_text='Instructions for Entry Gate')),
                ('exit_gate_info', models.TextField(help_text='Instructions for Exit Gate')),
                ('darshan_hall_info', models.TextField(help_text='Instructions for Darshan Hall')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
