# Generated by Django 5.2.10 on 2026-02-06 12:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('temples', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DarshanSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slot_type', models.CharField(choices=[('MORNING', 'Morning (6 AM - 11 AM)'), ('AFTERNOON', 'Afternoon (12 PM - 4 PM)'), ('NIGHT', 'Night (5 PM - 9 PM)')], max_length=10)),
                ('max_capacity', models.PositiveIntegerField(default=100)),
                ('reserved_count', models.PositiveIntegerField(default=0)),
                ('temple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temples.temple')),
            ],
            options={
                'unique_together': {('temple', 'date', 'slot_type')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ticket_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('USED', 'Used/Scanned'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='VALID', max_length=10)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.darshanslot')),
            ],
        ),
    ]
